
(function(window,document){"use strict";function applyCustomUi(jQuery,sk_threads_feed){jQuery('.sk_powered_by a').css({'background-color':getDsmSetting(sk_threads_feed,"post_background_color"),'color':getDsmSetting(sk_threads_feed,"post_font_color"),'font-size':getDsmSetting(sk_threads_feed,"details_font_size"),});sk_threads_feed.find('.sk-fb-event-item, .sk_powered_by').css({'margin-bottom':getDsmSetting(sk_threads_feed,"space_between_events")+'px'});sk_threads_feed.find(".loading-img").hide();sk_threads_feed.css({'width':'100%'});var sk_threads_feed_width=sk_threads_feed.innerWidth();sk_threads_feed.css({'height':'auto'});var column_count=sk_threads_feed.find('.column_count').text();var border_size=0;var background_color="#555555";var space_between_images=parseFloat(sk_threads_feed.find('.space_between_images').text());var margin_between_images=parseFloat(parseFloat(space_between_images).toFixed(0)/2)-parseFloat(1);var total_space_between_images=(parseFloat(space_between_images).toFixed(2)*parseFloat(column_count))+parseFloat(space_between_images);var pic_width=(parseFloat(sk_threads_feed_width).toFixed(0)-parseFloat(total_space_between_images).toFixed(0))/parseFloat(column_count).toFixed(0);var arrow_background_color="black";var arrow_color="white";var arrow_opacity=getDsmSetting(sk_threads_feed,"arrow_opacity");var css=".mfp-arrow-right:before { border-left: 27px solid "+arrow_background_color+" !important; }";css+=".fp-arrow-right:before {border-left: 27px solid "+arrow_background_color+" !important;}.mfp-arrow:after {border-top-width: 13px;border-bottom-width: 13px;top: 8px;}";css+=".mfp-arrow-right:after {opacity: "+arrow_opacity+"; border-left: 17px solid "+arrow_color+" !important;margin-left: 39px!important;}";css+=".mfp-arrow-left:after {opacity: "+arrow_opacity+"; border-right: 17px solid "+arrow_color+" !important;margin-left: 31px!important;}";css+=".mfp-arrow-left:before {margin-left: 25px!important;border-right: 27px solid "+arrow_background_color+" !important;}";var head=document.head||document.getElementsByTagName('head')[0];var style=document.createElement('style');head.appendChild(style);style.type='text/css';if(style.styleSheet){style.styleSheet.cssText=css;}else{style.appendChild(document.createTextNode(css));}
var sk_ig_all_posts_minus_spaces=parseFloat(sk_threads_feed_width).toFixed(2)-parseFloat(total_space_between_images).toFixed(2);var bottom_button_container_width=parseFloat(sk_threads_feed_width).toFixed(2)-(parseFloat(space_between_images).toFixed(2)*2);var bottom_button_width=parseFloat(sk_threads_feed_width).toFixed(2)/parseFloat(2).toFixed(2);var font_family=sk_threads_feed.find('.font_family').text();var details_bg_color=sk_threads_feed.find('.details_bg_color').text();var details_font_color=sk_threads_feed.find('.details_font_color').text();var details_link_color=sk_threads_feed.find('.details_link_color').text();var details_link_hover_color=sk_threads_feed.find('.details_link_hover_color').text();var button_bg_color=sk_threads_feed.find('.button_bg_color').text();var button_text_color=sk_threads_feed.find('.button_text_color').text();var button_hover_bg_color=sk_threads_feed.find('.button_hover_bg_color').text();var button_hover_text_color=sk_threads_feed.find('.button_hover_text_color').text();var post_separator_color=sk_threads_feed.find('.post_separator_color').text();var details_secondary_font_color=sk_threads_feed.find('.details_secondary_font_color').text();sk_threads_feed.css({'font-family':font_family,'font-size':getDsmSetting(sk_threads_feed,"details_font_size")+"px",'width':sk_threads_feed});sk_threads_feed.find('div').css({'font-family':font_family});if(sk_threads_feed.find(".grid-item-youtube-community").width()<300){sk_threads_feed.find('.word-date').hide();sk_threads_feed.find('.ago-date').show();}
jQuery('.sk-pop-ig-post, .sk-popup-post').css({'font-family':font_family});sk_threads_feed.find('.threads-user-root-container, .sk-tweet-text, .post-tweet-counts').css({'color':details_font_color});sk_threads_feed.find('.sk-secondary-data').css({'color':details_secondary_font_color,'font-family':font_family});sk_threads_feed.find('.sk-tweet-title').css({'font-family':font_family});sk_threads_feed.find('.threads-user-root-container a, .tweet-content a').css({'color':getDsmSetting(sk_threads_feed,"post_link_color")});sk_threads_feed.find(".threads-user-root-container a, .tweet-content a").mouseover(function(){$(this).css({'color':getDsmSetting(sk_threads_feed,"post_link_hover_color")});}).mouseout(function(){$(this).css({'color':getDsmSetting(sk_threads_feed,"post_link_color")});});sk_threads_feed.find('.sk-ww-youtube-community-item').css({'color':details_font_color,'border-top':'thin solid '+post_separator_color});sk_threads_feed.find(".sk-ww-youtube-community-item a").mouseover(function(){$(this).css({'color':details_link_hover_color});}).mouseout(function(){$(this).css({'color':details_link_color});});var margin_bottom_sk_ig_load_more_posts=space_between_images;if(margin_bottom_sk_ig_load_more_posts==0){margin_bottom_sk_ig_load_more_posts=5;}
sk_threads_feed.find(".sk-threads-load-more-posts").css({'margin-bottom':margin_bottom_sk_ig_load_more_posts+'px'});sk_threads_feed.find(".threads-user-container, .sk-threads-load-more-posts, .sk-threads-bottom-follow-btn").css({'background':button_bg_color,'border-color':button_bg_color,'color':button_text_color});sk_threads_feed.find(".threads-user-container, .sk-threads-load-more-posts, .sk-threads-bottom-follow-btn").mouseover(function(){$(this).css({'background-color':button_hover_bg_color,'border-color':button_hover_bg_color,'color':button_hover_text_color});}).mouseout(function(){$(this).css({'background':button_bg_color,'border-color':button_bg_color,'color':button_text_color});});var padding_sk_ig_bottom_btn_container=margin_between_images;if(padding_sk_ig_bottom_btn_container==0){padding_sk_ig_bottom_btn_container=5;}
sk_threads_feed.find(".sk-threads-bottom-btn-container").css({'padding':padding_sk_ig_bottom_btn_container+'px'});sk_threads_feed.find('.sk-youtube-community-description a').css({'color':details_link_color});sk_threads_feed.find(".sk-youtube-community-description a").mouseover(function(){$(this).css({'color':details_link_hover_color});}).mouseout(function(){$(this).css({'color':details_link_color});});sk_threads_feed.find('.sk-youtube-community-description strong').css({'color':details_font_color});if(getDsmSetting(sk_threads_feed,"show_view_on_threads_link")==0){sk_threads_feed.find('.view_on_threads_icon').hide();}
if(getDsmSetting(sk_threads_feed,"show_post_profile_image")==0){sk_threads_feed.find('.img-thumbnail').hide();}
if(getDsmSetting(sk_threads_feed,"show_post_profile_name")==0){sk_threads_feed.find('.sk-tweet-username').hide();}
sk_threads_feed.find('.sk-tweet-text, .post-tweet-counts, .sk_threads_feed_retweeted_by').css({'color':getDsmSetting(sk_threads_feed,"post_font_color")});sk_threads_feed.find('.sk-tweet-text a, .post-tweet-counts a').css({'color':getDsmSetting(sk_threads_feed,"post_link_color")});sk_threads_feed.find(".sk-tweet-text a, .post-tweet-counts a").mouseover(function(){$(this).css({'color':getDsmSetting(sk_threads_feed,"post_link_hover_color")});}).mouseout(function(){$(this).css({'color':getDsmSetting(sk_threads_feed,"post_link_color")});});sk_threads_feed.find('.sk-youtube-community-usename').css({'font-size':getDsmSetting(sk_threads_feed,"title_font_size")+"px"});var padding=getDsmSetting(sk_threads_feed,"item_content_padding");sk_threads_feed.find('.sk_popup_column_footer').css({'bottom':padding+'px'})
if(getDsmSetting(sk_threads_feed,"show_box_shadow")==1||getDsmSetting(sk_threads_feed,"show_box_shadow")==''){padding=parseInt(padding)?padding:30;if(jQuery(document).width()<480){padding=20;}
sk_threads_feed.find('.grid-content, .sk_popup_column_spacer').css({'box-shadow':'0 2px 5px 0 rgba(0,0,0,0.10)','-moz-box-shadow':'0 2px 5px 0 rgba(0,0,0,0.10)','-webkit-box-shadow':'0 2px 5px 0 rgba(0,0,0,0.10)','padding':padding+"px"});}
if(getDsmSetting(sk_threads_feed,"details_all_caps")==1){sk_threads_feed.css({'text-transform':'uppercase'});}
if(getDsmSetting(sk_threads_feed,"title_all_caps")==1){sk_threads_feed.find('.sk-youtube-community-usename').css({'text-transform':'uppercase'});}else{sk_threads_feed.find('.sk-youtube-community-usename').css({'text-transform':'none'});}
jQuery(document).find('.sk-ww-youtube-community').css({'background-color':getDsmSetting(sk_threads_feed,"details_bg_color")});sk_threads_feed.find('.grid-content').css({'background-color':getDsmSetting(sk_threads_feed,"post_background_color")});makeResponsive(jQuery,sk_threads_feed);var custom_css=getDsmSetting(sk_threads_feed,"custom_css");var font_family=getDsmSetting(sk_threads_feed,"font_family");custom_css=custom_css+" body .sk-ww-youtube-community button,input{ font-family : "+font_family+" !important}";jQuery('head').append('<style type="text/css">'+custom_css+'</style>');if(getDsmSetting(sk_threads_feed,"layout")==3){sk_threads_feed.find(".grid-youtube-community").css({"width":"92%","margin":"0px auto"});sk_threads_feed.find(".swiper-button-next,.swiper-button-prev").css({"border":"0px","background":"transparent","background-image":"none","outline":"none","font-size":"0px"});sliderLayoutUi(sk_threads_feed);}
var link_disabled_color=getDsmSetting(sk_threads_feed,'post_font_color');sk_threads_feed.find(".sk_threads_feed_data_post_item a").attr("target","_blank");disableLinks(sk_threads_feed,link_disabled_color);}
function makePopupLinksClickable(){jQuery('.sk-popup-post').find('.tweet-text').each(function(index,value){if(jQuery(value).hasClass("linkified")==false){replaceContentWithLinks(jQuery(value));jQuery(value).addClass("linkified");}});}
function disableLinks(sk_threads_feed,link_disabled_color){if(getDsmSetting(sk_threads_feed,"links_clickable")==0){var feed=jQuery.find(".grid-youtube-community, .threads-user-root-container");var feed_anchors=jQuery(feed).find("a");feed_anchors.removeAttr("href");feed_anchors.css({'color':link_disabled_color});sk_threads_feed.find("a").mouseover(function(){jQuery(this).css({'color':link_disabled_color});}).mouseout(function(){jQuery(this).css({'color':link_disabled_color});});setTimeout(function(){feed_anchors.css({'color':link_disabled_color});sk_threads_feed.find("a").mouseover(function(){jQuery(this).css({'color':link_disabled_color});}).mouseout(function(){jQuery(this).css({'color':link_disabled_color});});},500);setTimeout(function(){feed_anchors.css({'color':link_disabled_color});sk_threads_feed.find("a").mouseover(function(){jQuery(this).css({'color':link_disabled_color});}).mouseout(function(){jQuery(this).css({'color':link_disabled_color});});},1500);}}function loadCssFile(filename){var fileref=document.createElement("link");fileref.setAttribute("rel","stylesheet");fileref.setAttribute("type","text/css");fileref.setAttribute("href",filename);if(typeof fileref!="undefined"){document.getElementsByTagName("head")[0].appendChild(fileref)}}
function loadBioInformation(sk_threads_feed){var embed_id=getDsmEmbedId(sk_threads_feed);var show_profile_picture=sk_threads_feed.find('.show_profile_picture').text();var show_profile_username=sk_threads_feed.find('.show_profile_username').text();var show_profile_follow_button=sk_threads_feed.find('.show_profile_follow_button').text();var show_profile_posts_count=sk_threads_feed.find('.show_profile_posts_count').text();var show_profile_follower_count=sk_threads_feed.find('.show_profile_follower_count').text();var show_profile_following_count=sk_threads_feed.find('.show_profile_following_count').text();var show_profile_name=sk_threads_feed.find('.show_profile_name').text();var show_profile_description=sk_threads_feed.find('.show_profile_description').text();var show_profile_website=sk_threads_feed.find('.show_profile_website').text();var show_favorites_count=sk_threads_feed.find('.show_favorites_count').text();var posts_text=sk_threads_feed.find('.posts_text').text();var followers_text=sk_threads_feed.find('.followers_text').text();var following_text=sk_threads_feed.find('.following_text').text();var follow_text=sk_threads_feed.find('.follow_text').text();var favorites_text=sk_threads_feed.find('.favorites_text').text();var view_on_threads_text=sk_threads_feed.find('.view_on_threads_text').text();var post_items="";if(show_profile_picture==0&&show_profile_username==0&&show_profile_follow_button==0&&show_profile_posts_count==0&&show_profile_follower_count==0&&show_profile_following_count==0&&show_profile_name==0&&show_profile_description==0&&show_profile_website==0&&show_favorites_count==0){}else{if(original_data[embed_id].bio.name!=undefined){}}
return post_items;}
function loadFeed(sk_threads_feed){var embed_id=getDsmEmbedId(sk_threads_feed);var show_load_more_button=sk_threads_feed.find('.show_load_more_button').text();var load_more_posts_text=sk_threads_feed.find('.load_more_posts_text').text();var view_on_threads_text=sk_threads_feed.find('.view_on_threads_text').text();var follow_text=sk_threads_feed.find('.follow_text').text();var turnon_preapproval_posts=getDsmSetting(sk_threads_feed,'turnon_preapproval_posts');var predefined_search_keyword=getDsmSetting(sk_threads_feed,"predefined_search_keyword");if(original_data[embed_id].user_info&&!widgetValidation(sk_threads_feed,original_data[embed_id])){return;}
else if(!original_data[embed_id].bio&&!original_data[embed_id].posts){generateSolutionMessage(sk_threads_feed,embed_id);return;}
else{var post_items="";post_items+=loadBioInformation(sk_threads_feed);if(!original_data[embed_id].posts){original_data[embed_id].posts=[];}
original_data[embed_id].posts=moderateFilterByKeywords(sk_threads_feed,original_data[embed_id].posts);original_data[embed_id].posts=moderationTabFeature(sk_threads_feed,original_data[embed_id].posts,turnon_preapproval_posts);original_posts[embed_id]=original_data[embed_id].posts;data_storage[embed_id]=original_data[embed_id].posts;var current_data=[];if(getDsmSetting(sk_threads_feed,'layout')==3){post_items+=loadSliderLayout(sk_threads_feed,original_data[embed_id]);}
else{post_items+="<div class='grid-youtube-community'>";post_items+="<div class='grid-sizer-youtube-community'></div>";var enable_button=false;last_key[embed_id]=parseInt(getDsmSetting(sk_threads_feed,'post_count'));for(var i=0;i<last_key[embed_id];i++){if(typeof data_storage[embed_id][i]!='undefined'){current_data.push(data_storage[embed_id][i]);post_items+="<span class='sk_threads_feed_data_post_item'>";post_items+=getFeedItem(data_storage[embed_id][i],sk_threads_feed);post_items+="</span>";}}
if(data_storage[embed_id].length>last_key[embed_id]){enable_button=true;}
post_items+="</div>";if(show_load_more_button==1){post_items+="<div class='sk-threads-bottom-btn-container'>";if(show_load_more_button==1&&enable_button){post_items+="<button class='sk-threads-load-more-posts'>";post_items+=load_more_posts_text;post_items+="</button>";}
post_items+="</div>";}}
if(data_storage[embed_id].length==0){post_items+="<div class='sk-threads-bottom-btn-container'>";post_items+="No posts yet";post_items+="</div>";}
post_items+=skGetBranding(sk_threads_feed,original_data[embed_id].user_info);sk_threads_feed.append(post_items);let type=sk_threads_feed.find('.type').text();if(getDsmSetting(sk_threads_feed,'layout')==3){skLayoutSliderSetting(sk_threads_feed);}
replaceContentWithLinks(jQuery(".sk-youtube-community-description-"+embed_id+""));applyCustomUi(jQuery,sk_threads_feed);applyMasonry();fixMasonry();setTimeout(()=>{applyCustomUi(jQuery,sk_threads_feed);applyMasonry();fixMasonry();},1000);setTimeout(()=>{applyCustomUi(jQuery,sk_threads_feed);applyMasonry();fixMasonry();},2000);}
sk_increaseView(original_data[embed_id].user_info);}
function getFeedItem(val,sk_threads_feed){var embed_id=getDsmEmbedId(sk_threads_feed);var view_on_threads_text=sk_threads_feed.find('.view_on_threads_text').text();var show_post_image=sk_threads_feed.find('.show_post_image').text();var show_posts_on_threads=getDsmSetting(sk_threads_feed,"show_posts_on_threads");var column_count=getDsmSetting(sk_threads_feed,"column_count");var post_items="";var tweeter_post_link="https://www.youtube.com/"+val.link;var profile_picture=original_data[embed_id].bio.sk_profile_photo+"?v="+(new Date()).getTime();if(val.shortened_url&&val.shortened_url.length>0&&Array.isArray(val.shortened_url)&&val.images.length==0){val.shortened_url.forEach(element=>{val.images.push(element.images);});}
post_items+="<div class='grid-item-youtube-community grid-item-youtube-community-"+val.id+"'>";post_items+="<div class='mfp-hide sk-popup-post'>";post_items+="<div style='width:100%;'>";post_items+="<div class='sk_popup_row sk-media-post-container-"+val.id+"'>";if(val.video_url&&val.video_url.includes(".mp4")){post_items+="<div class='sk_popup_column sk_popup_column_media'>";post_items+="<video style='width:100%; height: 100%;' controls>";post_items+="<source src='"+val.video_url+"' type='video/mp4'>";post_items+="Your browser does not support HTML5 video.";post_items+="</video>";post_items+="</a>";post_items+="</div>";}
else if(val.images&&val.images.length>0){var images=val.images[0];if(images!=""){post_items+="<div class='sk_popup_column sk_popup_column_media'>";post_items+="<a href='"+images+"' target='_blank' class='"+popup_class+"' data-title=\""+image_caption+"\">";post_items+="<img src='"+images+"'  class='ig_media'/>";post_items+="</a>";post_items+="</div>";}}
post_items+="<div class='sk_popup_column sk_popup_column_description' >";post_items+="<div class='sk_popup_column_spacer'>";post_items+="<div class='sk_popup_column_user'>";post_items+="<img src='"+original_data[embed_id].bio.profile_photo+"'/>";post_items+="<p>";post_items+="<a class='href_status_trigger' href='https://www.youtube.com/"+val.screen_name+"/' target='_blank'><span>"+val.name+"</span></a>";post_items+="</p>";post_items+="</div>";post_items+="<div class='sk_popup_column_body'>";post_items+="<div class='sk_popup_column_body_content'>";post_items+=val.description;post_items+="</div>";post_items+="</div>";post_items+="<div class='sk_popup_column_footer'>";if(val.comments_count&&getDsmSetting(sk_threads_feed,"show_post_retweets_count")==1){post_items+="<div class='sk-post-retweet-count'>";post_items+="<span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf075;</span> "+val.comments_count;post_items+="</div>";}
if(val.likes_count&&getDsmSetting(sk_threads_feed,"show_post_likes_count")==1){post_items+="<div class='sk-post-favorite-count'>";post_items+="<span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf164;</span> "+val.likes_count;post_items+="</div>";}
if(getDsmSetting(sk_threads_feed,"show_view_on_twitter_link")==1){post_items+="<div class='sk-post-yt-logo'>";post_items+="<a class='href_status_trigger_post' href='https://www.youtube.com/post/"+val.id+"' target='_blank'><span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf16a;</span></a>";post_items+="</div>";}
if(val.ago_value&&getDsmSetting(sk_threads_feed,"show_post_date")==1){val.ago_value=val.ago_value.replace('a day ago','1d')
val.ago_value=val.ago_value.replace(' days ago','d')
val.ago_value=val.ago_value.replace('a month ago','1mo')
val.ago_value=val.ago_value.replace(' months ago','mo')
val.ago_value=val.ago_value.replace('a year ago','1y')
val.ago_value=val.ago_value.replace(' years ago','y')
post_items+="<span class='float-right'>";post_items+="<span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf017;</span> <span class='sk-comment-count'>"+val.ago_value+"</span>";post_items+="</span>";}
post_items+="</div>";post_items+="</div>";post_items+="</div>";post_items+="</div>";post_items+="</div>";post_items+="</div>";post_items+="<div class='grid-content'>";post_items+="<div class='tweet-content'>";if(getDsmSetting(sk_threads_feed,"show_post_profile_image")==1&&profile_picture){post_items+="<div class='tweet-image'>";post_items+="<img src='https://yt3.googleusercontent.com/ytc/AIdro_mBuT8zkOCdf6E9HhhUK8PNHWHvSolPICTLzfOE3AOfKMg=s160-c-k-c0x00ffffff-no-rj' class='img-thumbnail'>";post_items+="</div>";}
post_items+="<div class='tweet-header'>";var screen_name_ellypsis=val.screen_name;var font_size_class='';if(getDsmSetting(sk_threads_feed,"show_post_profile_image")==1){post_items+="<div class='sk-tweet-title sk-tweet-title-profile-enabled'>";}else{post_items+="<div class='sk-tweet-title sk-tweet-title'>";}
post_items+="<div class='sk-tweet-username'>";post_items+="<a class='href_status_trigger sk-youtube-community-tweet-user-name "+font_size_class+"' href='https://www.youtube.com/@"+val.screen_name+"' target='_blank'> "+val.name+"</a>";post_items+="<label class='sk-secondary-data sk-youtube-community-tweet-username "+font_size_class+"'>@"+screen_name_ellypsis+"</label>";post_items+="</div>";if(getDsmSetting(sk_threads_feed,"show_post_date")==1){post_items+="<div class='sk-secondary-data sk-post-date'><span class='show_time_in_pop_up'></span> "+val.ago_time+"</div>";}
post_items+="</div>";post_items+="</div>";var popup_class="sk-youtube-community-popup-image";if(show_posts_on_threads){popup_class="";post_items+="<div style='cursor: pointer;' onclick=\"window.open('"+tweeter_post_link+"');\" class='sk-youtube-community-container'>";}else{post_items+="<div class='sk-youtube-community-container'>";}
post_items+="<div class='sk-tweet-text sk-tweet-text-"+val.id+"'>";post_items+=val.description;post_items+="</div>";if(val.name=="1HiraethProject"){val.id=val.id+"_new";}
if(val.images&&val.images.length>0){if(show_post_image==1){var image_caption="";image_caption+="<div class='sk_threads_feed_pop_tweet_html'></div>";post_items+="<div class='sk-tweet-media'>";if(val.video_url&&val.video_url.includes(".mp4")){post_items+="<video style='width:100%;' controls>";post_items+="<source src='"+val.video_url+"' type='video/mp4'>";post_items+="Your browser does not support HTML5 video.";post_items+="</video>";}
else if(!Array.isArray(val.images)){post_items+="<a href='"+val.images+"' target='_blank' class='"+popup_class+"' data-title=\""+image_caption+"\">";post_items+="<img src='"+val.images+"' />";post_items+="</a>";}
else if(val.images){var width=val.images&&val.images.length>1?"w-50":"w-100";post_items+="<div class='d-flex'>";$.each(val.images,function(i,images){if(images!=""){post_items+="<div class='"+width+"'>";post_items+="<a href='"+images+"' target='_blank' class='"+popup_class+"' data-title=\""+image_caption+"\">";post_items+="<img src='"+images+"' />";post_items+="</a>";post_items+="</div>";}});post_items+="</div>";}
post_items+="</div>";}}
else if(val.url_meta&&!val.video_url&&val.url_meta.image_url&&val.url_meta.title&&val.url_meta.description){post_items+="<div id='sk_threads_feed_url_meta_"+val.id+"' class='sk_threads_feed_url_meta_holder'>";if(isTheLinkAYoutubeLink(val.url_meta.url)){var youtubeId=getYoutubeId(val.url_meta.url);post_items+="<iframe width='100%' src='https://www.youtube.com/embed/"+youtubeId+"' ></iframe>";}else{post_items+="<a class='href_status_trigger' href='"+val.url_meta.url+"' target='_blank'>";}
post_items+=val.url_meta.image_url?"<img class='sk_threads_feed_url_meta_image' src='"+val.url_meta.image_url+"' />":"";post_items+=val.url_meta.title?"<div class='sk_threads_feed_url_meta_title'>"+val.url_meta.title+"</div>":"";post_items+=val.url_meta.description?"<div class='sk_threads_feed_url_meta_description'>"+skThreadsFeed_nl2br(val.url_meta.description)+"</div>":"";if(!isTheLinkAYoutubeLink(val.url_meta.url)){post_items+="</a>";}
post_items+="</div>";}
else if(!val.video_url&&val.url){post_items+="<div id='sk_threads_feed_url_meta_"+val.id+"' class='sk_threads_feed_url_meta_holder'>";post_items+="</div>";}
post_items+="</div>";post_items+="<div class='post-tweet-counts'>";if(val.comments_count&&getDsmSetting(sk_threads_feed,"show_post_retweets_count")==1){post_items+="<div class='sk-post-retweet-count'>";post_items+="<span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf075;</span> "+val.comments_count;post_items+="</div>";}
if(val.likes_count&&getDsmSetting(sk_threads_feed,"show_post_likes_count")==1){post_items+="<div class='sk-post-favorite-count'>";post_items+="<span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf164;</span> "+val.likes_count;post_items+="</div>";}
if(getDsmSetting(sk_threads_feed,"show_view_on_twitter_link")==1){post_items+="<div class='sk-post-yt-logo'>";post_items+="<a class='href_status_trigger_post' href='https://www.youtube.com/post/"+val.id+"' target='_blank'><span style='font-family: FontAwesome !important;' aria-hidden='true'>&#xf16a;</span></a>";post_items+="</div>";}
post_items+="</div>";post_items+="</div>";post_items+="</div>";post_items+="</div>";return post_items;}
function requestFeedData(sk_threads_feed){var embed_id=getDsmEmbedId(sk_threads_feed);var json_url=app_file_server_url+embed_id+".json?nocache="+(new Date()).getTime();jQuery.getJSON(json_url,function(data){original_data[embed_id]=data;loadFeed(sk_threads_feed);}).fail(function(e){generateSolutionMessage(sk_threads_feed,embed_id);});}var $grid;var env_urls=skGetEnvironmentUrls('youtube-community');var app_url=env_urls.app_url;var sk_app_url=env_urls.sk_app_url;var sk_api_url=env_urls.sk_api_url;var app_backend_url=env_urls.app_backend_url;var app_file_server_url=env_urls.app_file_server_url;var sk_img_url=env_urls.sk_img_url;var data_storage={};var last_key={};var original_posts={};var original_data={};var additional_error_messages=["<li>Please make sure your Threads username is correct.</li>","<li>Make sure your account is public.</li>","<li>Make sure your account is not suspended.</li>"];var el=document.getElementsByClassName('sk-ww-youtube-community')[0];el.innerHTML="<div class='first_loading_animation' style='text-align:center; width:100%;'><img src='"+app_url+"images/ripple.svg' class='loading-img' style='width:auto !important;' /></div>";if(window.jQuery===undefined||window.jQuery.fn.jquery!=='2.1.1'){var script_tag=document.createElement('script');script_tag.setAttribute("type","text/javascript");script_tag.setAttribute("src","https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js");if(script_tag.readyState){script_tag.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){scriptLoadHandler();}};}else{script_tag.onload=scriptLoadHandler;}
(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(script_tag);}else{jQuery=window.jQuery;scriptLoadHandler();}
loadCssFile(app_url+"libs/js/magnific-popup/magnific-popup.css");loadCssFile("https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css");function loadScript(url,callback){var scriptTag=document.createElement('script');scriptTag.setAttribute("type","text/javascript");scriptTag.setAttribute("defer","defer");scriptTag.setAttribute("async","async");scriptTag.setAttribute("src",url);if(typeof callback!=="undefined"){if(scriptTag.readyState){scriptTag.onreadystatechange=function(){if(this.readyState==='complete'||this.readyState==='loaded'){callback();}};}else{scriptTag.onload=callback;}}
(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(scriptTag);}
function scriptLoadHandler(){loadScript(app_url+"libs/js/magnific-popup/jquery.magnific-popup.js",function(){loadScript(app_url+"libs/js/masonry/masonry4.2.2.min.js",function(){loadScript(app_url+"libs/js/swiper/swiper.min.js",function(){loadScript(app_url+"libs/js/imagesloaded.js",function(){$=jQuery=window.jQuery.noConflict(true);main();});});});});}
function hidePopUp(){if(jQuery.magnificPopup){jQuery.magnificPopup.close();}}
function showPopup(jQuery,content_src,clicked_element){jQuery('video').each(function(){jQuery(this)[0].pause();});jQuery('.sk_selected_popup').removeClass('sk_selected_popup');clicked_element.addClass('sk_selected_popup');var sk_threads_feed=clicked_element.closest('.sk-ww-youtube-community');hidePopUp();if(typeof jQuery.magnificPopup==="undefined")
initManificPopupPlugin(jQuery);if(getDsmSetting(sk_threads_feed,'show_posts_on_threads')!=1){jQuery.magnificPopup.open({items:{src:content_src},'type':'inline',callbacks:{open:function(){var post_html="";if(clicked_element.prev('.sk_threads_feed_data_post_item').length){post_html+="<button class='prev_popup'>";post_html+="<i class='fa fa-chevron-left sk_prt_4px' aria-hidden='true'></i>";post_html+="</button>";}
if(clicked_element.next('.sk_threads_feed_data_post_item').length){post_html+="<button class='next_popup'>";post_html+="<i class='fa fa-chevron-right sk_plt_4px' aria-hidden='true'></i>";post_html+="</button>";}
jQuery('.sk-popup-post').prepend(post_html);var white_popup=jQuery('.mfp-content').find('.sk-popup-post');makePopupLinksClickable();if(jQuery('.mfp-content .sk_popup_column_media').length==0){jQuery('.mfp-content .sk_popup_column_description').css('width','100%');}
if(getDsmSetting(sk_threads_feed,"links_clickable")==1){makePopupLinksClickable();white_popup.find('.sk_popup_column_user span').css({'font-size':getDsmSetting(sk_threads_feed,'details_font_size'),});white_popup.find('.sk_popup_column').css({'background':getDsmSetting(sk_threads_feed,'pop_up_bg_color'),'color':getDsmSetting(sk_threads_feed,'pop_up_font_color'),'font-size':getDsmSetting(sk_threads_feed,'details_font_size'),});white_popup.find('.sk_popup_column a').css({'color':getDsmSetting(sk_threads_feed,'pop_up_link_color'),});}else{var link_disabled_color=getDsmSetting(sk_threads_feed,'post_font_color')
disableLinks(white_popup,link_disabled_color);}
let item_content_padding=parseInt(getDsmSetting(sk_threads_feed,'item_content_padding'));var popup_height=white_popup.find('.ig_media').height();var popup_desc_height=popup_height;if(sk_threads_feed.width()<480){item_content_padding=20;}
else{popup_desc_height-=item_content_padding*2;}
if(jQuery(document).height()>480){white_popup.find('.sk_popup_column_description, .sk_popup_column_media').height(popup_height);white_popup.find('.sk_popup_column_spacer').height(popup_desc_height);}
white_popup.find('.sk_popup_column_spacer').css({'padding':item_content_padding+'px'})
var sk_popup_column_body_width=white_popup.find('.sk_popup_column_body').width();white_popup.find('.sk_popup_column_body_content').width(sk_popup_column_body_width-10);white_popup.find('.sk_popup_column_body').mouseover(function(){var sk_popup_column_body_height=jQuery(this).height();var sk_popup_column_body_content_height=jQuery(this).find('.sk_popup_column_body_content').height();if(sk_popup_column_body_height<sk_popup_column_body_content_height){jQuery(this).css({'overflow':'hidden scroll'});}}).mouseout(function(){jQuery(this).css({'overflow':'hidden'});});var popup_height=white_popup.find('.sk_popup_row').height();var popup_bio_height=white_popup.find('.sk_popup_column_user').height();if(jQuery(document).width()>=480){white_popup.find('.sk_popup_column_body').height(350);}},close:function(){jQuery(".prev_popup, .next_popup").remove();jQuery('video').each(function(){$(this)[0].pause();});}}});}}
function applyMasonry(){if(jQuery('.grid-item-youtube-community').length==0){return;}
if(!window.Masonry){loadScript(app_url+"libs/js/masonry/masonry4.2.2.min.js",function(){});}
$grid=new Masonry('.grid-youtube-community',{itemSelector:'.grid-item-youtube-community',columnWidth:'.grid-sizer-youtube-community',percentPosition:true,transitionDuration:0});var sk_threads_feed=jQuery('.sk-ww-youtube-community');}
function fixMasonry(){window.setInterval(function(){applyMasonry();},1000);}
function makeResponsive(jQuery,sk_threads_feed){var sk_threads_feed_width=sk_threads_feed.width();if(sk_threads_feed_width<150){sk_threads_feed_width=jQuery(document).width();}
var grid_sizer_item=33.3;if(sk_threads_feed_width<=320){centerProfileWhenMobile(sk_threads_feed);grid_sizer_item=100;}
else if(sk_threads_feed_width<=481){centerProfileWhenMobile(sk_threads_feed);grid_sizer_item=100;}
else if(sk_threads_feed_width<=641){if(getDsmSetting(sk_threads_feed,"column_count")==1){grid_sizer_item=100;}
else{grid_sizer_item=50;}}
else if(sk_threads_feed_width<=930){if(getDsmSetting(sk_threads_feed,"column_count")==1){grid_sizer_item=100;}
else if(getDsmSetting(sk_threads_feed,"column_count")==2){grid_sizer_item=50;}
else{grid_sizer_item=33.3}}
else{if(getDsmSetting(sk_threads_feed,"column_count")==1){grid_sizer_item=100;}
else if(getDsmSetting(sk_threads_feed,"column_count")==2){grid_sizer_item=50;}
else if(getDsmSetting(sk_threads_feed,"column_count")==3){grid_sizer_item=33;}
else if(getDsmSetting(sk_threads_feed,"column_count")==4){grid_sizer_item=25;}}
sk_threads_feed.find(".grid-sizer-youtube-community, .grid-item-youtube-community").css({"width":grid_sizer_item+"%"});if(sk_threads_feed.find(".grid-item-youtube-community").width()<300){sk_threads_feed.find('.word-date').hide();sk_threads_feed.find('.ago-date').show();}
else{sk_threads_feed.find('.word-date').show();sk_threads_feed.find('.ago-date').hide();}
if(getDsmSetting(sk_threads_feed,'layout')==1||getDsmSetting(sk_threads_feed,'layout')==3){var imgs=sk_threads_feed.find('img');var len=imgs.length;if(imgs.prop('complete')){setTimeout(function(){fixGridHeight(sk_threads_feed);},50);}
else if(imgs.length>0){var counter=0;[].forEach.call(imgs,function(img){img.addEventListener('load',function(){counter++;if(counter==len){setTimeout(function(){fixGridHeight(sk_threads_feed);},500);}},false);});}
else{fixGridHeight(sk_threads_feed);}}
applyMasonry();}
function centerProfileWhenMobile(sk_threads_feed){sk_threads_feed.find('.youtube-community-pic').css({"margin":"0 auto","float":"none"});sk_threads_feed.find('.sk-youtube-community-usename').css({"float":"none"});sk_threads_feed.find('.sk-youtube-community-info').css({"width":"100%","text-align":"center",});sk_threads_feed.find('.sk-youtube-community-count-item').css({"width":"50%",});}
function fixGridHeight(sk_threads_feed){var padding=getDsmSetting(sk_threads_feed,"item_content_padding");padding=parseInt(padding)?padding:30;if(jQuery(document).width()<480){padding=20;}
var post_height=getDsmSetting(sk_threads_feed,"post_height");if(post_height<100){post_height=100;}
sk_threads_feed.find(".post-tweet-counts").css({'position':'absolute','bottom':padding+'px',});sk_threads_feed.find(".sk-post-date").css({'float':'none',});sk_threads_feed.find(".sk-youtube-community-container").height(post_height);var maxHeight=0;sk_threads_feed.find(".grid-content").each(function(){var this_H=jQuery(this).outerHeight(true);if(maxHeight<this_H){maxHeight=this_H;}});if(getDsmSetting(sk_threads_feed,'layout')==3){maxHeight=post_height;}
sk_threads_feed.find('.grid-content').height(maxHeight);sk_threads_feed.find(".grid-content").each(function(){var this_1=jQuery(this).find('.sk_threads_feed_retweeted_by').height();var this_2=jQuery(this).find('.tweet-header').height();this_1=this_1?this_1:0;this_2=this_2?this_2:0;var this_3=maxHeight-this_1-this_2-50;jQuery(this).find(".sk-youtube-community-container").height(this_3);});sk_threads_feed.find(".sk-youtube-community-container").mouseover(function(){var container_height=jQuery(this).closest(".grid-content").find(".sk-tweet-text").height();if(jQuery(this).closest(".grid-content").find(".sk-tweet-media").length>0){container_height=container_height+jQuery(this).closest(".grid-content").find(".sk-tweet-media").height();}
if(jQuery(this).closest(".grid-content").find(".sk_threads_feed_url_meta_holder").length>0){container_height=container_height+jQuery(this).closest(".grid-content").find(".sk_threads_feed_url_meta_holder").height();}
if(jQuery(this).height()<container_height){jQuery(this).css({"overflow-y":"scroll","overflow-x":"hidden"});}}).mouseout(function(){jQuery(this).css({"overflow-y":"hidden","overflow-x":"hidden"});});sk_threads_feed.find(".sk-youtube-community-container").css({"overflow":"hidden"});setTimeout(function(){sk_threads_feed.find(".sk-tweet-media, .sk-tweet-text").css({"width":sk_threads_feed.find(".sk-youtube-community-container").width()-10+"px"});sk_threads_feed.find(".sk-link-article-container").css({"width":sk_threads_feed.find(".sk-youtube-community-container").width()-10+"px"});sk_threads_feed.find(".sk-link-article-container").css({"width":sk_threads_feed.find(".sk-youtube-community-container").width()-10+"px"});applyMasonry();},500);}
function loadSliderLayout(sk_threads_feed,data){var post_items="<div id='sk_threads_feed_slider' class='swiper-container swiper-layout-slider'>";post_items+="<div class='swiper-wrapper' style='background-color: transparent !important'>";var data_slider=data.posts;var column_count=getDsmSetting(sk_threads_feed,"column_count");if(jQuery(document).width()<480){column_count=1;}
else if(jQuery(document).width()<750){column_count=column_count==1?1:2;}
else if(jQuery(document).width()<970){column_count=column_count==1?1:3;}
var pages=Math.ceil(data_slider.length/column_count);for(var slide=1;slide<=pages;slide++){post_items+="<div class='swiper-slide'>";post_items+="<div class='grid-youtube-community'>";post_items+="<div class='grid-sizer-youtube-community'></div>";var data_posts_count=0;var post_count=getDsmSetting(sk_threads_feed,"post_count");var slider_data=getPaginationResult(sk_threads_feed,data_slider,slide,column_count)
jQuery.each(slider_data,function(key,val){post_items+="<span class='sk_threads_feed_data_post_item'>";if(val){post_items+=getFeedItem(val,sk_threads_feed);}
post_items+="</span>";data_posts_count++;});post_items+="</div>";post_items+="</div>";}
post_items+="</div>";post_items+="<button type='button' class='swiper-button-next ' style='pointer-events: all;'>";post_items+="<i class='sk_arrow sk_right_arrow'></i>";post_items+="</button>";post_items+="<button type='button' class='swiper-button-prev' style='pointer-events: all;'>";post_items+="<i class='sk_arrow sk_left_arrow'></i>";post_items+="</button>";post_items+="</div>";return post_items;}
function getPaginationResult(sk_threads_feed,tweets_data,page,column_count){var start=0;var end=parseInt(column_count);var multiplicand=page-1;var return_tweets_data=[];if(page!=1){start=multiplicand*end;end=start+end;}
if((end-1)>tweets_data.length){end=tweets_data.length;}
for(var i=start;i<end;i++){return_tweets_data.push(tweets_data[i]);}
return return_tweets_data;}
function skLayoutSliderSetting(sk_threads_feed){var swiper=new Swiper('.sk-ww-youtube-community .swiper-container',{navigation:{nextEl:'.sk-ww-youtube-community .swiper-button-next',prevEl:'.sk-ww-youtube-community .swiper-button-prev',},});}
function sliderLayoutUi(sk_threads_feed){var arrow_background_color=getDsmSetting(sk_threads_feed,"arrow_background_color");var arrow_color=getDsmSetting(sk_threads_feed,"arrow_color");var arrow_opacity=getDsmSetting(sk_threads_feed,"arrow_opacity");sk_threads_feed.find(".sk_arrow").css({"border":"solid "+arrow_color,"border-width":"0 3px 3px 0","opacity":arrow_opacity,"color":arrow_color,"background-color":"transparent"});jQuery(".swiper-button-next,.swiper-button-prev").mouseover(function(){jQuery(this).find(".sk_arrow").css({"border":"solid "+arrow_background_color,"border-width":"0 3px 3px 0"});jQuery(this).css({"opacity":"1","color":arrow_background_color});}).mouseout(function(){jQuery(this).find(".sk_arrow").css({"border":"solid "+arrow_color,"border-width":"0 3px 3px 0"});jQuery(this).css({"opacity":arrow_opacity});});sk_threads_feed.find(".swiper-button-prev,.swiper-button-next").css({"background-color":"transparent","opacity":arrow_opacity,"color":arrow_color});sk_threads_feed.find(".swiper-button-prev").css({"left":"-10px"});sk_threads_feed.find(".threads-user-root-container").css({"width":"92%","margin":"0 auto",});}
function moderateFilterByKeywords(sk_threads_feed,data_storage_param){var embed_id=getDsmEmbedId(sk_threads_feed);var is_keyword_valid=typeof getDsmSetting(sk_threads_feed,"predefined_search_keyword")!=='undefined'&&getDsmSetting(sk_threads_feed,"predefined_search_keyword").trim().length>0;if(is_keyword_valid){var new_posts_list=[];var keywords=getDsmSetting(sk_threads_feed,"predefined_search_keyword").trim().split(',');for(let item of data_storage_param){for(var i=0;i<keywords.length;i++){if(item.description.toLowerCase().includes(keywords[i].toLowerCase())){new_posts_list.push(item);}}}
data_storage_param=new_posts_list;}
return data_storage_param;}
function moderationTabFeature(sk_threads_feed,data_storage_param,turnon_preapproval_posts){var embed_id=getDsmEmbedId(sk_threads_feed);var preapproved_posts=[];var excluded_posts=[];if(turnon_preapproval_posts==1){if(getDsmSetting(sk_threads_feed,"preapproved_posts")!=""){preapproved_posts=getDsmSetting(sk_threads_feed,"preapproved_posts").split(",");}}else if(getDsmSetting(sk_threads_feed,"excluded_posts")!=""){excluded_posts=getDsmSetting(sk_threads_feed,"excluded_posts").split(",");}
var new_posts_list=[];for(let item of data_storage_param){if(item){if(getDsmSetting(sk_threads_feed,'turnon_preapproval_posts')==1){if(preapproved_posts.indexOf(item.id)!=-1){new_posts_list.push(item);}}
else{if(getDsmSetting(sk_threads_feed,'turnon_preapproval_posts')==0&&excluded_posts.indexOf(item.id)!=-1){}
else{new_posts_list.push(item);}}}};return new_posts_list;}
function skThreadsFeed_nl2br(str,is_xhtml){if(typeof str==='undefined'||str===null){return'';}
var breakTag=(is_xhtml||typeof is_xhtml==='undefined')?'<br />':'<br>';return(str+'').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,'$1'+breakTag+'$2');}
function showThreadsData(posts,type,show_thumbnail=1){jQuery.each(posts,function(key,val){val.id=val.id.replace("&","and_sign");val.id=val.id.replace(".","dot");var meta_holder=jQuery("#sk_threads_feed_url_meta_"+val.id);if(val.url&&meta_holder.length&&val.video_url==""){showUrlData(meta_holder,val.url,val.id,type,show_thumbnail);}});}
function maxChars(str,max){var tags=0,sQuotes=0,dQuotes=0,char,count=0,result=[];for(var i=0,len=str.length;i<len;++i){char=str.charAt(i);switch(char){case'<':if(!sQuotes&&!dQuotes){++tags;result.push(char);continue;}
break;case'>':if(!sQuotes&&!dQuotes){--tags;result.push(char);continue;}
break;case"'":if(tags&&!dQuotes)
sQuotes=!sQuotes;break;case'"':if(tags&&!sQuotes)
dQuotes=!dQuotes;break;}
if(tags){result.push(char);}else{if(++count<max)
result.push(char);}}
return result.join('');}
function replaceContentWithLinks(html){if(html.hasClass("linkified")){return;}
html.addClass("linkified")
var text=html.html();if(text){text=text.replace(/(\r\n|\n\r|\r|\n)/g,"<br>");text=text.split("<br>").join(" <br> ");text=replaceHttpToLink(text);text=text.split(">https://ess.com<").join(">ess.com<");var splitted_text=text.split(' ');if(splitted_text&&splitted_text.length>0){jQuery.each(splitted_text,function(key,value){if(value.charAt(0)=="#"){var original_text=value.replace('#','');original_text=original_text.replace(/^\,+|\,+$/g,'');original_text=original_text.replace("</div>",'');if(key==splitted_text.length-1){text=text.replace(' '+value,' <a target="_blank" href="http://facebook.com/hashtag/'+original_text+'">'+value+'</a>');}
else{text=text.replace(value+' ','<a target="_blank" href="http://facebook.com/hashtag/'+original_text+'">'+value+'</a> ');}}
else if(value.charAt(0)=="@"){var original_text=value.replace('@','');text=text.replace(value+' ',' <a target="_blank" href="http://facebook.com/'+original_text+'">'+value+'</a> ');}
if(value.indexOf("sec.state")!=-1){text=text.replace(value+' ',' <a target="_blank" href="https://'+value+'">'+value+'</a> ');}});}
html.html(text);}}
function replaceURLWithDisplayURL(html,orig_url,shortened_url,display_url){if(html.length<1)
return;var text=html.html();if(shortened_url&&display_url&&text.length>0&&text.indexOf(shortened_url)!=-1){text=text.replace(shortened_url,orig_url);text=text.replace(shortened_url,display_url);}
else if(shortened_url){text=text.replace(shortened_url,"");text=text.replace(shortened_url,"");}
html.html(text);}
function replaceHttpToLink(content)
{return content;}
function isTheLinkAYoutubeLink(url){var youtubeUrl="youtube.com/watch?";var youtubeUrl2="youtu.be";if(typeof url==="undefined"){return false;}
if(url.indexOf(youtubeUrl)>=0||url.indexOf(youtubeUrl2)>=0){return true;}else{return false;}}
function getYoutubeId(url){var regExp=/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;var match=url.match(regExp);if(match&&match[2].length==11){return match[2];}else{return'error';}}
function getDsmEmbedId(sk_threads_feed){var embed_id=sk_threads_feed.attr('embed-id');if(embed_id==undefined){embed_id=sk_threads_feed.attr('data-embed-id');}
return embed_id;}
function getDsmSetting(sk_threads_feed,key){return sk_threads_feed.find("."+key).text();}
function formatDate(date){date=new Date(date.replace(" ","T"))
var months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];return date.getDate()+" "+months[date.getMonth()]+" "+date.getFullYear();}
function formatTimeFromDate(date){date=new Date(date.replace(" ","T"));var hours=date.getHours();var minutes=date.getMinutes();var ampm=hours>=12?'PM':'AM';hours=hours%12;hours=hours?hours:12;minutes=minutes<10?'0'+minutes:minutes;var formatted_time=hours+':'+minutes+' '+ampm;return formatted_time;}
function formatNumber(num){return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g,'$1,')}
function convertToUrl(str){let url=str;const pattern=/^(ftp|http|https):\/\/[^ "]+$/;if(!pattern.test(url)){url='https://'+url;}
return url;}function loadGoogleFont(font_family){var web_safe_fonts=["Inherit","Impact, Charcoal, sans-serif","'Palatino Linotype', 'Book Antiqua', Palatino, serif","Century Gothic, sans-serif","'Lucida Sans Unicode', 'Lucida Grande', sans-serif","Verdana, Geneva, sans-serif","Copperplate, 'Copperplate Gothic Light', fantasy","'Courier New', Courier, monospace","Georgia, Serif"];if(!web_safe_fonts.includes(font_family)){try{loadCssFile("https://fonts.googleapis.com/css?family="+font_family);}catch(error){}}}
function readableNumber(number){number=parseInt(number);number=number?number.toLocaleString("en-US"):0;return number;}
function addDescriptiveTagAttributes(_sk,add_to_img=true){_sk.find('a').each(function(i,v){var title=jQuery(v).text();if(!jQuery(v).attr('title')){jQuery(v).attr('title',title);}});if(add_to_img){_sk.find('img').each(function(i,v){var src=jQuery(v).attr('src');jQuery(v).attr('alt','Post image');});}}
function getClientId(){var _gaCookie=document.cookie.match(/(^|[;,]\s?)_ga=([^;,]*)/);if(_gaCookie)return _gaCookie[2].match(/\d+\.\d+$/)[0];}
function getSkEmbedId(sk_class){var embed_id=sk_class.attr('embed-id');if(embed_id==undefined){embed_id=sk_class.attr('data-embed-id');}
return embed_id;}
function getSkSetting(sk_class,key){return sk_class.find("div."+key).text();}
function setCookieSameSite(){document.cookie="AC-C=ac-c;expires=Fri, 31 Dec 2025 23:59:59 GMT;path=/;HttpOnly;SameSite=Lax";}
function getIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0)
return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)));else if(!!navigator.userAgent.match(/Trident\/7\./))
return 11;else
return 0;}
function isSafariBrowser(){var ua=navigator.userAgent.toLowerCase();if(ua.indexOf('safari')!=-1){if(ua.indexOf('chrome')>-1){return 0;}else{return 1;}}}
if(getIEVersion()>0||isSafariBrowser()>0){loadIEScript('https://cdn.jsdelivr.net/bluebird/3.5.0/bluebird.min.js');loadIEScript('https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.js');}
function loadIEScript(url){var scriptTag=document.createElement('script');scriptTag.setAttribute("type","text/javascript");scriptTag.setAttribute("src",url);(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(scriptTag);}
function kFormatter(num){return Math.abs(num)>999?Math.sign(num)*((Math.abs(num)/1000).toFixed(1))+'k':Math.sign(num)*Math.abs(num)}
function sk_increaseView(user_info){try{if(user_info&&user_info.status&&(user_info.status==1||user_info.status==6||user_info.status==7||user_info.status==13)){jQuery.getJSON('https://api.ipify.org?format=json',function(data){var update_views_url="https://views.accentapi.com/add_view.php?user_id="+user_info.id+"&url="+document.URL+"&ip_address="+data.ip+"&embed_id="+user_info.embed_id;if(app_url.includes("local")&&sk_app_url){update_views_url="https://localtesting.com/accentapiviews/add_view.php?user_id="+user_info.id+"&url="+document.URL+"&ip_address="+data.ip+"&embed_id="+user_info.embed_id;}
jQuery.ajax(update_views_url);});}}
catch(err){console.log("Error retrieving ip address.");}}
function isTooDarkColor(hexcolor){var r=parseInt(hexcolor.substr(1,2),16);var g=parseInt(hexcolor.substr(3,2),16);var b=parseInt(hexcolor.substr(4,2),16);if(hexcolor.indexOf('rgb')!=-1){let rgbstr=hexcolor;let v=getRGB(rgbstr);r=v[0];g=v[1];b=v[2];}
b=isNaN(b)?0:b;var yiq=((r*299)+(g*587)+(b*114))/1000;if(yiq<60){}
else{}
return yiq<60?true:false;}
function linkify(html){var temp_text=html.split("https://www.").join("https://");temp_text=temp_text.split("www.").join("https://www.");var exp=/((href|src)=["']|)(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;return temp_text.replace(exp,function(){return arguments[1]?arguments[0]:"<a href=\""+arguments[3]+"\">"+arguments[3]+"</a>"});}
function skGetEnvironmentUrls(folder_name){var scripts=document.getElementsByTagName("script");var scripts_length=scripts.length;var search_result=-1;var other_result=-1;var app_url="https://widgets.sociablekit.com/";var app_backend_url="https://api.accentapi.com/v1/";var app_file_server_url="https://data.accentapi.com/feed/";var sk_app_url="https://sociablekit.com/app/";var sk_api_url="https://api.sociablekit.com/";var sk_img_url="https://images.sociablekit.com/";var sk_fb_sync_url="https://facebook-sync.sociablekit.com/";for(var i=0;i<scripts_length;i++){var src_str=scripts[i].getAttribute('src');if(src_str!=null){var other_folder="";if(folder_name=='facebook-page-playlists'){other_folder='facebook-page-playlist';}
else if(folder_name=='linkedin-page-posts'){other_folder='linkedin-page-post';}
else if(folder_name=='linkedin-profile-posts'){other_folder='linkedin-profile-post';}
else if(folder_name=='facebook-hashtag-posts'){other_folder='facebook-hashtag-feed';}
else if(folder_name=='facebook-page-events'){other_folder='facebook-events';}
else if(folder_name=='facebook-page-posts'){other_folder='facebook-feed';if(document.querySelector(".sk-ww-facebook-feed")){var element=document.getElementsByClassName("sk-ww-facebook-feed")[0];element.classList.add("sk-ww-facebook-page-posts");}}
other_result=src_str.search(other_folder);search_result=src_str.search(folder_name);if(search_result>=1||other_result>=1){var src_arr=src_str.split(folder_name);app_url=src_arr[0];app_url=app_url.replace("displaysocialmedia.com","sociablekit.com");if(app_url.search("local")>=1){app_backend_url="http://localhost:3000/v1/";app_url="https://localtesting.com/SociableKIT_Widgets/";app_file_server_url="https://localtesting.com/SociableKIT_FileServer/feed/";sk_app_url="https://localtesting.com/SociableKIT/";sk_api_url="http://127.0.0.1:8000/";sk_img_url="https://localtesting.com/SociableKIT_Images/";sk_fb_sync_url="https://localtesting.com/SociableKIT_Facebook_Sync/";}
else{app_url="https://widgets.sociablekit.com/";}}}}
return{"app_url":app_url,"app_backend_url":app_backend_url,"app_file_server_url":app_file_server_url,"sk_api_url":sk_api_url,"sk_app_url":sk_app_url,"sk_img_url":sk_img_url,"sk_fb_sync_url":sk_fb_sync_url};}
function changeBackSlashToBR(text){if(text){for(var i=1;i<=10;i++){text=text.replace('\n','</br>');}}
return text;}
function sKGetScrollbarWidth(){var outer=document.createElement('div');outer.style.visibility='hidden';outer.style.overflow='scroll';outer.style.msOverflowStyle='scrollbar';document.body.appendChild(outer);var inner=document.createElement('div');outer.appendChild(inner);var scrollbarWidth=(outer.offsetWidth-inner.offsetWidth);outer.parentNode.removeChild(outer);return scrollbarWidth;}
function isValidURL(url){const urlPattern=/^(http(s)?:\/\/)?(www\.)?[a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$/;return urlPattern.test(url);}
async function showUrlData(element,url,post_id,type="",show_thumbnail=1){element.hide();var check_url=url&&url.includes('&')?encodeURIComponent(url):url;var free_data_url=app_file_server_url.replace("feed/","get_fresh_url_tags.php")+'?post_id='+post_id+'&url='+check_url;var read_one_url=app_file_server_url.replace("feed","url-tags")+post_id+".json";if(jQuery('.sk_version').text()){read_one_url+="?v="+jQuery('.sk_version').text();}
fetch(read_one_url,{method:'get',cache:'no-cache'}).then(async response=>{if(response.ok){let data=await response.json();if(data&&data.status&&data.status==418){displayUrlData(data,element,type,show_thumbnail,post_id);data=await jQuery.ajax(free_data_url);}
return data;}
else{response=await jQuery.ajax(free_data_url);displayUrlData(response,element,type,show_thumbnail,post_id);return response;}}).then(async response=>{if(response!=undefined){displayUrlData(response,element,type,show_thumbnail,post_id);}else{response=await jQuery.ajax(free_data_url);displayUrlData(response,element,type,show_thumbnail,post_id);}}).catch(async error=>{var data=await jQuery.ajax(free_data_url);displayUrlData(data,element,type,show_thumbnail,post_id);});}
async function displayUrlData(response,element,type,show_thumbnail=1,post_id){var meta_holder=jQuery(element);var html="";if(!response||response.error){if(meta_holder.html()){meta_holder.show();}
return;}
if(response.message&&response.message=="Data not available. Please try again."){return;}
if(response.messages&&response.messages.length>0&&response.messages[0]=="PDF files that are over 10Mb are not supported by Google Docs Viewer"){var data=response.url;if(response.url){data=response.url.replace("https://","").split("/");}
if(data.length>0){if(data.length>1){response.title=data[data.length-1];}
response.description=data[0].replace("www.","");}}
if(post_id=="7059257055500492800"){response.url+="?id=122630";}
if(response.html&&meta_holder.closest('.sk-ww-twitter-feed').length>0){html+=response.html;}else if(response.title&&response.title.includes("NCBI - WWW Error Blocked Diagnostic")){console.log(meta_holder);html+="<a href='"+meta_holder.data('link')+"' link-only target='_blank'>";html+="<div class='sk-link-article-container' style='background: #eeeeee;color: black !important; font-weight: bold !important; border-radius: 2px; border: 1px solid #c3c3c3; box-sizing: border-box; word-wrap: break-word;'>";if(show_thumbnail==1){html+="<image alt='No alternative text description for this image' class='sk-link-article-image sk_post_img_link' onerror='this.style.display=\"none\"' src='"+meta_holder.data('image')+"'/>";}
if(response.title){html+="<div class='sk-link-article-title' style='padding: 8px;'>"+meta_holder.data('title')+"</div>";}
html+="</div>";html+="</a>";}
else{html+="<a href='"+response.url+"' link-only target='_blank'>";html+="<div class='sk-link-article-container' style='background: #eeeeee;color: black !important; font-weight: bold !important; border-radius: 2px; border: 1px solid #c3c3c3; box-sizing: border-box; word-wrap: break-word;'>";if(show_thumbnail==1){html+="<image alt='No alternative text description for this image' class='sk-link-article-image sk_post_img_link' onerror='this.style.display=\"none\"' src='"+response.thumbnail_url+"'/>";}
if(response.title){html+="<div class='sk-link-article-title' style='padding: 8px;'>"+response.title+"</div>";}
else if(response.url&&response.url.indexOf(".pdf")!=-1){html+=response.html;}
if(type&&type==6){if(response.description&&response.description.length>0){response.description=response.description.length>140?response.description.substring(0,140)+' ...':response.description;}}
if(response.description&&response.description.indexOf("[vc_row]")!==-1&&response.url){var pathArray=response.url.split('/');var protocol=pathArray[0];if(pathArray.length>2){var host=pathArray[2];var url=protocol+'//'+host;html+="<div class='sk-link-article-description' style='padding: 8px;color: grey;font-weight: 100;font-size: 14px;'>"+url+"</div>";}}
else if(response.description&&response.description.indexOf("fb_built")==-1&&response.description!="null"){if(response.url){var domain=new URL(response.url).hostname;response.description=domain;}
html+="<div class='sk-link-article-description' style='padding: 8px;color: #000000;font-weight: 100;font-size: 14px;'>"+response.description+"</div>";}
else if(response.url&&response.url.includes('instagram.com/p/')){html+="<image style='padding: 8px;' alt='No alternative text description for this image' class='sk-ig-default' onerror='this.style.display=\"none\"' src='https://i1.wp.com/sociablekit.com/wp-content/uploads/2019/01/instagram.png'/>";html+="<div class='sk-link-article-description' style='padding: 8px;margin-left:15%;color: #000000;font-weight: 600;font-size: 14px;'>View this post in instagram</div>";html+="<div class='sk-link-article-description' style='padding: 0px 8px ;margin-left:15%;margin-bottom:10px;color: #000000;font-weight: 100;font-size: 10px;'>"+response.url+"</div>";}
html+="</div>";html+="</a>";}
meta_holder.html(html);meta_holder.css('display','block');meta_holder.css('margin-bottom','15px');meta_holder.find('.sk-ig-default').closest('.sk-link-article-container').css('display','inline-block');meta_holder.find('.sk-ig-default').closest('.sk-link-article-container').css('width','100%');meta_holder.find('.sk-ig-default').css('width','20%');meta_holder.find('.sk-ig-default').css('float','left');applyMasonry();}
function slugifyString(str){str=str.replace(/^\s+|\s+$/g,'');str=str.toLowerCase();var from="ÃÃ„Ã‚Ã€ÃƒÃ…ÄŒÃ‡Ä†ÄŽÃ‰ÄšÃ‹ÃˆÃŠáº¼Ä”È†ÃÃŒÃŽÃÅ‡Ã‘Ã“Ã–Ã’Ã”Ã•Ã˜Å˜Å”Å Å¤ÃšÅ®ÃœÃ™Ã›ÃÅ¸Å½Ã¡Ã¤Ã¢Ã Ã£Ã¥ÄÃ§Ä‡ÄÃ©Ä›Ã«Ã¨Ãªáº½Ä•È‡Ã­Ã¬Ã®Ã¯ÅˆÃ±Ã³Ã¶Ã²Ã´ÃµÃ¸Ã°Å™Å•Å¡Å¥ÃºÅ¯Ã¼Ã¹Ã»Ã½Ã¿Å¾Ã¾ÃžÄÄ‘ÃŸÃ†aÂ·/_,:;";var to="AAAAAACCCDEEEEEEEEIIIINNOOOOOORRSTUUUUUYYZaaaaaacccdeeeeeeeeiiiinnooooooorrstuuuuuyyzbBDdBAa------";for(var i=0,l=from.length;i<l;i++){str=str.replace(new RegExp(from.charAt(i),'g'),to.charAt(i));}
str=str.replace(/[^a-z0-9 -]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-');return str;}
function skGetBranding(sk_,user_info){sk_.find('.sk_branding').remove();sk_.find('div.user_email').remove();var html="";if(!user_info)
return;var slugify_string="";if(user_info.solution_name){slugify_string=slugifyString(user_info.solution_name);user_info.tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string+"-website/";if(user_info.website_builder){user_info.tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string;slugify_string=slugifyString(user_info.website_builder);user_info.tutorial_link=user_info.tutorial_link+"-"+slugify_string;}}
if(user_info.type==9){user_info.tutorial_link="https://www.sociablekit.com/sync-facebook-page-events-to-google-calendar/";}
else if(user_info.type==26){user_info.tutorial_link="https://www.sociablekit.com/how-to-sync-facebook-group-events-to-google-calendar-on-website/";}
if(user_info.show_branding&&(user_info.show_branding==1||user_info.show_branding=="true")||user_info.show_branding==true){var fontFamily=getSkSetting(sk_,"font_family");var link_color=getSkSetting(sk_,"details_link_color");var details_bg_color=getSkSetting(sk_,"details_bg_color");if(link_color==""){link_color="rgb(52, 128, 220)";}
if(details_bg_color&&isTooDarkColor(link_color)==false&&isTooDarkColor(details_bg_color)==false){link_color='#3480dc';}
var temporary_tutorial_link=user_info.tutorial_link;if(temporary_tutorial_link.endsWith("/")==false){temporary_tutorial_link=temporary_tutorial_link+"/";}
var linkedin_widgets=[33,34,44,58,75,99,100,103];if(linkedin_widgets.includes(user_info.type)&&user_info.embed_id%2==1){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-linkedin-feed-"+website_builder+"/";}
if(user_info.type==5&&user_info.embed_id%2==1){temporary_tutorial_link=temporary_tutorial_link.replace("profile","feed")}
var facebook_feed=[1,4,9,10,11,36,38,43,12,24,26,49,2,8,3,18,19,28,30,61];if(facebook_feed.includes(user_info.type)&&user_info.embed_id%2==1){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-facebook-feed-"+website_builder+"/";}
var threads_feed=[110];if(threads_feed.includes(user_info.type)&&user_info.embed_id%2==0){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-threads-"+website_builder+"/";}
var nofollow_attribute="";if(window.location.href.includes("clean-concept-plus")){nofollow_attribute="rel='nofollow'";}}
return html;}
function getRGB(rgbstr){return rgbstr.substring(4,rgbstr.length-1).replace(/ /g,'').replace('(','').split(',');}
function freeTrialEndedMessage(solution_info){var sk_error_message="<div class='sk_trial_ended_message'>";sk_error_message+="Customized feed is powered by <strong><a href='https://www.sociablekit.com/' target='_blank'>SociableKIT</a></strong>.<br>";sk_error_message+="If you're the owner of this website, your 7-day Free Trial has ended.<br>";sk_error_message+="If you want to continue using our services, please <strong><a target='_blank' href='https://www.sociablekit.com/app/users/subscription/subscription'>subscribe now</a></strong>.";sk_error_message+="</div>";return sk_error_message;}
function privateFBGroupMessage(){var sk_error_message="<div class='sk_trial_ended_message'>";sk_error_message+="<h2>The Facebook group is private, it must be <a target='_blank' href='https://www.facebook.com/community/using-key-groups-tools/understanding-your-privacy-settings/'>public</a>.</h2>";sk_error_message+="</div>";return sk_error_message;}
function isFreeTrialEnded(start_date){var start_date=new Date(start_date);var current_date=new Date();var difference=current_date.getTime()-start_date.getTime();difference=parseInt(difference/(1000*60*60*24));return difference>7?true:false;}
function unableToLoadSKErrorMessage(solution_info,additional_error_messages){var sk_error_message="<ul class='sk_error_message'>";sk_error_message+="<li><a href='"+solution_info.embed_id+"' target='_blank'>Customized "+solution_info.solution_name+" feed by SociableKIT</a></li>";console.log(solution_info);sk_error_message+="<li>Unable to load "+solution_info.solution_name+".</li>";for(var i=0;i<additional_error_messages.length;i++){sk_error_message+=additional_error_messages[i];}
sk_error_message+="<li>If you think there is a problem, <a target='_blank' href='https://go.crisp.chat/chat/embed/?website_id=2e3a484e-b418-4643-8dd2-2355d8eddc6b'>chat with support here</a>. We will solve it for you.</li>";sk_error_message+="</ul>";return sk_error_message;}
function widgetValidation(_sk,data){if(data.user_info){var user_info=data.user_info;user_info.trial_ended=false;user_info.show_feed=user_info.show_feed==="false"?false:true;if(user_info.status==7&&user_info.cancellation_date){var cancellation_date=new Date(user_info.cancellation_date).setHours(0,0,0,0);var current_date=new Date().setHours(0,0,0,0);user_info.show_feed=current_date>cancellation_date?false:true;var activation_date=new Date(user_info.activation_date).setHours(0,0,0,0);if(activation_date>cancellation_date){user_info.show_feed=true;}
if(!user_info.show_feed){var sk_error_message=generateBlueMessage(_sk,user_info);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}}
else if(user_info.status==0||user_info.status==2||user_info.status==10){user_info.show_feed=false;}
if(user_info.type==43||user_info.type==38||user_info.type==50){var sk_error_message="<div class='sk_error_message'>";sk_error_message+="<p style='text-align: center !important; margin: 1rem'>"+user_info.solution_name+" are currently unavailable, please choose another <a href='https://www.sociablekit.com/demos/' target='_blank'>widget here</a></p>";sk_error_message+="</div>";_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
else if(!user_info.show_feed){var sk_error_message=generateBlueMessage(_sk,user_info);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
else if(user_info.widget_status==1){var sk_error_message=generateBlueMessage(_sk,user_info);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
return user_info.show_feed;}}
function generateBlueMessage(_sk,user_info){var tutorial_link="";var sk_error_message="";if(user_info.solution_name){var slugify_string=slugifyString(user_info.solution_name);tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string+"-website/";}
if(user_info.type==9){tutorial_link="https://www.sociablekit.com/sync-facebook-page-events-to-google-calendar/";}
else if(user_info.type==26){tutorial_link="https://www.sociablekit.com/how-to-sync-facebook-group-events-to-google-calendar-on-website/";}
if(user_info.widget_status==1){var sk_error_message="<div class='sk_error_message'>";sk_error_message+="<p style='text-align: center !important; margin: 1rem'> The widget does not exist. If you think this is a mistake, please contact support</a></p>";sk_error_message+="</div>";return sk_error_message;}
if(user_info.show_feed==false){if(!user_info.message||user_info.message==""){var sk_error_message="<ul class='sk_error_message'>";sk_error_message+="<li><a href='"+tutorial_link+"' target='_blank'>"+user_info.solution_name+" powered by SociableKIT</a></li>";sk_error_message+="<li>If youâ€™re the owner of this website or SociableKIT account used, we found some errors with your account.</li>";sk_error_message+="<li>Please login your SociableKIT account to fix it.</li>";sk_error_message+="</ul>";user_info.message=sk_error_message;}
sk_error_message=user_info.message;}
else if(user_info.solution_name==null&&user_info.type==null&&user_info.start_date==null){sk_error_message="<p class='sk_error_message'>";sk_error_message+="The SociableKIT solution does not exist. If you think this is a mistake, please contact support.";sk_error_message+="</p>";}
else{sk_error_message="<div class='sk_error_message'>";sk_error_message+="<div style='display: inline-flex;width:100%;'>";sk_error_message+="<div>";sk_error_message+="<h4>SociableKIT is currently syncing your <a href='"+tutorial_link+"' target='_blank'>"+user_info.solution_name+" widget.</a></h4>";sk_error_message+=`<svg width="480"height="20"><rect x="0"y="0"width="480"height="20"fill="#f0f0f0"rx="10"ry="10"/><pattern id="stripes"x="0"y="0"width="20"height="20"patternUnits="userSpaceOnUse"patternTransform="rotate(45)"><rect x="0"y="0"width="10"height="20"fill="#007bff"/></pattern><rect id="progressBar"x="0"y="0"width="0"height="20"fill="url(#stripes)"rx="10"ry="10"><animate attributeName="width"attributeType="XML"from="0"to="480"dur="2s"repeatCount="indefinite"/></rect></svg>`;sk_error_message+="<p>While waiting there are a few things you need to know:</p>";sk_error_message+="<ul>";sk_error_message+="<li>It usually takes only a few minutes. We appreciate your patience.</li>";sk_error_message+="<li>We will notify you via email once your "+user_info.solution_name+" feed is ready.</li>";if(user_info.type==5){sk_error_message+="<li>Make sure your instagram account <a target='_blank' href='https://www.instagram.com/"+getDsmSetting(_sk,'username')+"' target='_blank'><b>@"+getDsmSetting(_sk,'username')+"</b></a> is connected.</li>";}
else if(user_info.type==22||user_info.type==39){sk_error_message+="<li>Please make sure that you selected the correct Google Place or that the <a href='https://www.sociablekit.com/how-to-identify-google-place-id/' target='blank'><b> Google Place ID </b></a> you entered is correct.</li>";}
else{sk_error_message+="<li>Please make sure that the <b> Source ID/Username </b> you enter is correct.</li>";}
sk_error_message+="<li>If you think there is a problem, <a target='_blank' href='https://go.crisp.chat/chat/embed/?website_id=2e3a484e-b418-4643-8dd2-2355d8eddc6b'>chat with support here</a>. We will solve it for you.</li>";sk_error_message+="</ul>";sk_error_message+="</div>";sk_error_message+="</div>";sk_error_message+="</div>";}
return sk_error_message;}
function generateSolutionMessage(_sk,embed_id){var json_url=sk_api_url+"api/user_embed/info/"+embed_id;var sk_error_message="";jQuery.getJSON(json_url,function(data){if(data.type==1&&data.encoded==true){loadEvents(_sk);}
else if(data.type==44&&data.encoded==true){loadFeed(_sk);}
else if(data.type==58&&data.encoded==true){var no_data_text=_sk.find('.no_data_text').text();_sk.html("<div style='padding: 20px;text-align: center;'>"+no_data_text+"</div>");}
else if(data.type==67&&data.encoded==true){loadEvents(_sk);}
else if(data.type==74&&data.encoded==true){_sk.html("<div>No jobs yet, please try again later.</div>");}
else if((data.type==12||data.type==26||data.type==24||data.type==49)&&data.encoded==true){_sk.html(privateFBGroupMessage());}
else{var sk_error_message=generateBlueMessage(_sk,data);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);}}).fail(function(e){console.log(e);});}
function copyInput(copy_button,copy_input){var copy_button_orig_html=copy_button.html();copy_input.select();try{var successful=document.execCommand('copy');var msg=successful?'successful':'unsuccessful';if(msg=='successful'){copy_button.html("<i class='fa fa-clipboard'></i> Copied!");setTimeout(function(){copy_button.html(copy_button_orig_html);},3000);}
else{alert('Copying text command was '+msg+'.');}}
catch(err){alert('Oops, unable to copy.');}}
function getDefaultLinkedInPageProfilePicture(profile_picture){if(profile_picture&&profile_picture.indexOf("data:image/gif")!=-1){profile_picture="https://gmalcilk.sirv.com/iamge.JPG";}
return profile_picture;}
function detectedSKDashboard(){let parent_url=(window.location!=window.parent.location)?document.referrer:document.location.href;if(parent_url&&(parent_url.indexOf("sociablekit.com")!=-1||parent_url.indexOf("local")!=-1)){return true;}
return false;}
function getSKDashboardPremiumTrialMessage(){var sk_error_message="";sk_error_message+="<ul class='sk_error_message'>";sk_error_message+="<li>Your 7-days premium trial has ended.</li>";sk_error_message+="<li>Please purchase a <a href='https://www.sociablekit.com/app/users/subscription/subscription?action=subscribe_now'>SociableKIT subscription plan</a> ";sk_error_message+="to save your widget customizations, save time with automatic sync, enjoy priority support, and get a 50% discount on any annual plans. Donâ€™t miss out!</li>";sk_error_message+="<li>You may also choose to <a href='https://help.sociablekit.com/en-us/article/how-to-activate-the-free-plan-1l3o0nt/'>activate the free plan</a> if you don't need our premium features.</li>";sk_error_message+="</ul>";return sk_error_message;}
function getSocialIcon(category)
{var post_items='';if(category.indexOf("Facebook")!=-1){post_items+="<i class='fab fa-facebook' aria-hidden='true'></i>";}
else if(category.indexOf("Instagram")!=-1){post_items+="<i class='fab fa-instagram' aria-hidden='true'></i>";}
else if(category.indexOf("Linkedin")!=-1){post_items+="<i class='fab fa-linkedin' aria-hidden='true'></i>";}
else if(category.indexOf("Youtube")!=-1){post_items+="<i class='fab fa-youtube' aria-hidden='true'></i>";}
else if(category.indexOf("Google")!=-1){post_items+="<i class='fab fa-google' aria-hidden='true'></i>";}
else if(category.indexOf("Twitter")!=-1){post_items+='<i class="fa-brands fa-x-twitter"></i>';}
else if(category.indexOf("Twitch")!=-1){post_items+="<i class='fab fa-twitch' aria-hidden='true'></i>";}
else if(category.indexOf("Yelp")!=-1){post_items+="<i class='fab fa-yelp' aria-hidden='true'></i>";}
else if(category.indexOf("Vimeo")!=-1){post_items+="<i class='fab fa-vimeo' aria-hidden='true'></i>";}
else if(category.indexOf("Twitch")!=-1){post_items+="<i class='fab fa-twitch' aria-hidden='true'></i>";}
else if(category.indexOf("Trust")!=-1){post_items+="<i class='fab fa-trustpilot' aria-hidden='true'></i>";}
else if(category.indexOf("Spot")!=-1){post_items+="<i class='fab fa-spotify' aria-hidden='true'></i>";}
return post_items;}
function isFontAwesomeLoaded(){var span=document.createElement('span');span.className='fa';span.style.display='none';document.body.insertBefore(span,document.body.firstChild);var font=css(span,'font-family');if(font.indexOf("fontawesome")==-1){return false;}
document.body.removeChild(span);return true;}
function css(element,property){let font=window.getComputedStyle(element,null).getPropertyValue(property);if(font){font=font.toLowerCase();return font.replace(/' '/g,"");}
return'na';}function readImageUrl(sk_class_,image,identifier,index,folder_name=false,version=null){var widget_version=sk_class_.find('div.widget_version').text();if(!sk_img_url){return;}
var image_thumbnail=encodeURIComponent(image);var image_url=sk_img_url.replace('feed/','')+"images/"+identifier+".jpg";if(folder_name){folder_name="images/"+folder_name;var image_url=sk_img_url.replace('feed/','')+folder_name+"/"+identifier+".jpg";}
if(widget_version&&widget_version=="update"){saveImageUrl(sk_class_,image_thumbnail,identifier,image_url,folder_name);return;}
fetch(image_url).then(function(response){if(status.status==200){displayImageData(sk_class_,identifier,image_url);}else{jQuery("<img>").attr('src',image_url).on('load',()=>displayImageData(sk_class_,identifier,image_url)).on('error',()=>saveImageUrl(sk_class_,image_thumbnail,identifier,image_url,folder_name));}}).catch(function(){saveImageUrl(sk_class_,image_thumbnail,identifier,image_url,folder_name);});}
function displayImageData(sk_class_,identifier,image_url){if(sk_class_.find('div.widget_version').text()){image_url=image_url+"?v="+sk_class_.find('div.widget_version').text();}
sk_class_.find('div[data-image="'+identifier+'"] img').attr('src',image_url);sk_class_.find('div[data-image="'+identifier+'"]').css({"background-image":"url("+image_url+")"});sk_class_.find('img[data-image="'+identifier+'"]').attr('src',image_url);}
function saveImageUrl(sk_class_,image_thumbnail,identifier,image_url,folder_name){var embed_id=getDsmEmbedId(sk_class_);if(!folder_name){folder_name='images';}
var sync_url=sk_img_url+'saving_image.php?file_name='+identifier+'&image_url='+image_thumbnail+'&folder='+folder_name+'&save_image=images';fetch(sync_url).then(function(){displayImageData(sk_class_,identifier,image_url);}).catch(function(){console.log("Cant save:",identifier)});}function main(){function loadSettingsData(sk_threads_feed,json_settings_url,json_feed_url,embed_id){fetch(json_feed_url,{method:'get'}).then(function(response){if(!response.ok){loadSettingsData(sk_threads_feed,json_settings_url,json_settings_url,embed_id)
return;}
response.json().then(function(data){var settings_data=data;original_data[embed_id]=data;if(data.settings){settings_data=data.settings;}
if(!settings_data.type){loadSettingsData(sk_threads_feed,json_settings_url,json_settings_url,embed_id)
return;}
var web_safe_fonts=["Inherit","Impact, Charcoal, sans-serif","'Palatino Linotype', 'Book Antiqua', Palatino, serif","Century Gothic, sans-serif","'Lucida Sans Unicode', 'Lucida Grande', sans-serif","Verdana, Geneva, sans-serif","Copperplate, 'Copperplate Gothic Light', fantasy","'Courier New', Courier, monospace","Georgia, Serif"];var is_font_included=web_safe_fonts.indexOf(settings_data.font_family);if(is_font_included<0){loadCssFile("https://fonts.googleapis.com/css?family="+settings_data.font_family);}
if(data.css){jQuery('head').append('<style type="text/css">'+data.css+'</style>');}
else{var sk_version=settings_data.sk_version?settings_data.sk_version:1.0;loadCssFile(app_url+"youtube-community/widget_css.php?v="+sk_version);}
if(data.show_feed==false){sk_threads_feed.prepend(settings_data.message);sk_threads_feed.find('.loading-img').hide();sk_threads_feed.find('.first_loading_animation').hide();}
else{var settings_html="";settings_data.post_count=settings_data.post_count?settings_data.post_count:10;settings_html+="<div class='display-none sk-threads-settings' style='display:none;'>";jQuery.each(settings_data,function(key,value){settings_html+="<div class='"+key+"'>"+value+"</div>";});settings_html+="</div>";sk_threads_feed.prepend(settings_html);if(getDsmSetting(sk_threads_feed,'layout')==3){loadCssFile(app_url+"libs/swiper/swiper.min.css");loadCssFile(app_url+"libs/swiper/swiper.css?v=ranndomchars");}
settings_html="";if(data.settings){loadFeed(sk_threads_feed);}
else{requestFeedData(sk_threads_feed)}}});}).catch(function(err){loadSettingsData(sk_threads_feed,json_settings_url,json_settings_url,embed_id);});}
jQuery(document).ready(function($){jQuery('.sk-ww-youtube-community').each(function(){var sk_threads_feed=jQuery(this);var embed_id=getDsmEmbedId(sk_threads_feed);var new_sk_threads_feed_width=jQuery(window).height()+100;sk_threads_feed.height(new_sk_threads_feed_width);var json_settings_url=app_file_server_url.replace('feed','')+"settings/"+embed_id+"/settings.json?nocache="+(new Date()).getTime();var json_feed_url=app_file_server_url+embed_id+".json?nocache="+(new Date()).getTime();loadSettingsData(sk_threads_feed,json_settings_url,json_feed_url,embed_id);});jQuery(document).on('click','.device_btn, #expand',function(){applyCustomUi(jQuery,jQuery('.sk-ww-youtube-community'));});jQuery(document).on('click','.sk-ww-youtube-community .sk-youtube-community-container',function(e){var clicked_element=jQuery(this);var clicked_element=jQuery(this).closest('.sk_threads_feed_data_post_item');var content_src=clicked_element.find('.sk-popup-post:first');const hasClass=e.target.classList.contains('description');const hasClass_image=e.target.classList.contains('article-image');if(e.target.tagName==='A'){return;}
if(hasClass||hasClass_image){return;}
e.preventDefault();showPopup(jQuery,content_src,clicked_element);return false;});jQuery(document).on('click','.sk-popup-post .prev_popup',function(){var clicked_element=jQuery(this);var clicked_element=jQuery('.sk_selected_popup').prev('.sk_threads_feed_data_post_item');if(clicked_element.index()<0){return;}
var content_src=clicked_element.find('.sk-popup-post:first');showPopup(jQuery,content_src,clicked_element);});jQuery(document).on('click','.sk-popup-post .next_popup',function(){var clicked_element=jQuery(this);var clicked_element=jQuery('.sk_selected_popup').next('.sk_threads_feed_data_post_item');if(clicked_element.index()<0){return;}
var content_src=clicked_element.find('.sk-popup-post:first');showPopup(jQuery,content_src,clicked_element);});jQuery(document).on('click','.new_tabslinks',function(){var clicked_element=jQuery(this);var sk_threads_feed=jQuery('.sk-ww-youtube-community');if(sk_threads_feed){setTimeout(function(){applyCustomUi(jQuery,sk_threads_feed);},1000);}});jQuery(window).resize(function(){jQuery('.sk-ww-youtube-community').each(function(){var sk_threads_feed=jQuery(this);sk_threads_feed.css({'width':'100%'});applyCustomUi(jQuery,sk_threads_feed);});});jQuery(document).on('click','.sk-ww-youtube-community .sk-threads-load-more-posts',function(){if(jQuery(this).attr('disabled')=="disabled"){return false;}
jQuery(this).attr('disabled','disabled');var current_btn=jQuery(this);var current_btn_text=current_btn.text();var sk_threads_feed=jQuery(this).closest('.sk-ww-youtube-community');var embed_id=getDsmEmbedId(sk_threads_feed);jQuery(this).html("<i class='fa fa-spinner fa-pulse' aria-hidden='true'></i>");setTimeout(function(){var post_items="";var enable_button=false;var old_last_key=last_key[embed_id];last_key[embed_id]=old_last_key+parseInt(getDsmSetting(sk_threads_feed,'post_count'));var current_data=[];for(var i=old_last_key;i<last_key[embed_id];i++){if(typeof data_storage[embed_id][i]!='undefined'){current_data.push(data_storage[embed_id][i]);post_items+="<span class='sk_threads_feed_data_post_item'>";post_items+=getFeedItem(data_storage[embed_id][i],sk_threads_feed);post_items+="</span>";}}
if(data_storage[embed_id].length>last_key[embed_id]){enable_button=true;}
sk_threads_feed.find('.grid-youtube-community').append(post_items);current_btn.html(current_btn_text);if(enable_button){sk_threads_feed.find('.sk-threads-load-more-posts').show();}else{sk_threads_feed.find('.sk-threads-load-more-posts').hide();}
showThreadsData(current_data,getDsmSetting(sk_threads_feed,"type"),getDsmSetting(sk_threads_feed,"show_post_image"));jQuery.each(current_data,function(key,val){replaceContentWithLinks(jQuery(".sk-tweet-text-"+val.id));});applyCustomUi(jQuery,sk_threads_feed);applyMasonry();fixMasonry();current_btn.removeAttr('disabled');},500);});jQuery(document).on('click','.sk-ww-youtube-community .sk-watermark',function(){jQuery('.sk-ww-youtube-community .sk-message').slideToggle();});});}}(window,document));